#!/usr/bin/env python3
"""
ARC Version Split Utility
==========================

Helper to distinguish ARC-AGI-1 vs ARC-AGI-2 tasks in your training data.

Usage:
    from arc_version_split import is_arc1_task, is_arc2_new_task, get_arc1_tasks, get_arc2_new_tasks

    # Check individual task
    if is_arc1_task('00576224'):
        print("This is from ARC-AGI-1")

    # Filter tasks by version
    arc1_ids = get_arc1_tasks(all_task_ids)
    arc2_ids = get_arc2_new_tasks(all_task_ids)

    # Compute separate scores
    arc1_score = compute_score(predictions, arc1_ids)
    arc2_score = compute_score(predictions, arc2_ids)
"""

# ARC-AGI-1 task IDs (391 tasks that made it into ARC-AGI-2)
# Generated by comparing with original ARC-AGI repo
with open('arc1_task_ids.txt', 'r') as f:
    ARC1_TASK_IDS = set(line.strip() for line in f if line.strip())

# ARC-AGI-2 new task IDs (609 new tasks)
with open('arc2_new_task_ids.txt', 'r') as f:
    ARC2_NEW_TASK_IDS = set(line.strip() for line in f if line.strip())

# Tasks removed from ARC-1 (9 tasks)
with open('arc1_removed_task_ids.txt', 'r') as f:
    ARC1_REMOVED_TASK_IDS = set(line.strip() for line in f if line.strip())


def is_arc1_task(task_id: str) -> bool:
    """Check if task ID is from ARC-AGI-1."""
    return task_id in ARC1_TASK_IDS


def is_arc2_new_task(task_id: str) -> bool:
    """Check if task ID is new in ARC-AGI-2."""
    return task_id in ARC2_NEW_TASK_IDS


def was_removed_from_arc1(task_id: str) -> bool:
    """Check if task was in ARC-1 but removed in ARC-2."""
    return task_id in ARC1_REMOVED_TASK_IDS


def get_arc1_tasks(task_ids):
    """Filter list/set of task IDs to only ARC-AGI-1 tasks."""
    return [tid for tid in task_ids if is_arc1_task(tid)]


def get_arc2_new_tasks(task_ids):
    """Filter list/set of task IDs to only ARC-AGI-2 new tasks."""
    return [tid for tid in task_ids if is_arc2_new_task(tid)]


def get_version_stats():
    """Print statistics about task distribution."""
    return {
        'arc1_tasks': len(ARC1_TASK_IDS),
        'arc2_new_tasks': len(ARC2_NEW_TASK_IDS),
        'arc1_removed_tasks': len(ARC1_REMOVED_TASK_IDS),
        'total_training': len(ARC1_TASK_IDS) + len(ARC2_NEW_TASK_IDS)
    }


if __name__ == '__main__':
    stats = get_version_stats()
    print('ARC Version Distribution')
    print('=' * 50)
    print(f"ARC-AGI-1 tasks (in ARC-2 training): {stats['arc1_tasks']}")
    print(f"ARC-AGI-2 new tasks:                  {stats['arc2_new_tasks']}")
    print(f"ARC-AGI-1 removed tasks:              {stats['arc1_removed_tasks']}")
    print(f"Total ARC-2 training tasks:           {stats['total_training']}")
    print('=' * 50)
    print(f"\nPercentage from ARC-1: {100*stats['arc1_tasks']/stats['total_training']:.1f}%")
    print(f"Percentage new in ARC-2: {100*stats['arc2_new_tasks']/stats['total_training']:.1f}%")
